#include <Arduino.h>
#include "settings.h"

const char H_HOME_PAGE[] PROGMEM = {
  //  this is the page frame for all webpages
  //  all pages should be generated by replacing the {pagename}-fields width
  //  the webpages for the particular pages
  "<!DOCTYPE html>"
  "<html lang=\"de\">"
  "<head>"
  "<meta charset=\"utf-8\">"
  "<TITLE>{title}</TITLE>"
  "<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.5\">"
  "<style>"
  "body {"
    "  font-family: Verdana, sans-serif;"
    "  font-size: 87.5%;"
    "  background-color: #e8e8e8;"
    "  color: black;"
    "  padding: 0;"
    "  margin:0;"
  "}"

  "div1 {"
    "  width: 100%;"
    "  color: black;"
    "  padding: 10px;"
    "  position: absolute;"
    "  top: 60px;"
    "  left: 150px;"
  "}"

  ".vertical-menu a {"
    "  background-color: #b9d8e9;"
    "  color: black;"
    "  display: block;"
    "  padding: 12px;"
    "  text-decoration: none;"
  "}"

  ".vertical-menu {"
    "  width: 100px;"
    "  background-color: #e8e8e8;" //menuefarbe ???
  "}"

  ".vertical-menu a:hover {"
    "  background-color: #4CAFf0;"
  "}"

  ".vertical-menu a.active {"
    "  background-color: #4CAFf0;"
    "  color: white;"
  "}"

  "</style>"
  "</head>"
  "<body>"

  "<h1>{hostname}</h1>"
  "<div1>{content}</div1>"
  "<div class=\"vertical-menu\">"
  "<a href=\"info\">Info</a><br>"
  "{appmenu}"
  "{mainpage}"
  "{confpage}"
  "</div>"
  "</body>"
  "</html>"};

const char H_APPMENU[] PROGMEM = {
  "<a href=\"status\">Status</a><br>"
  "{appmenu}"};

const char H_STATUSMENU[] PROGMEM = {
  "<a href=\"on\">Ein</a><br>"
  "<a href=\"off\">Aus</a><br>"
   };

const char H_INFOMENU[] PROGMEM = {
  "<a href=\"config\">Config</a><br>"
  "<a href=\"showlog\">show log</a>"
  "<a href=\"showdir\">show Dir</a>"
  };

const char H_CONFMENUMEAS[] PROGMEM = {
  "<a href=\"meascyc\">MeasCyc</a>"
  "<a href=\"transcyc\">TransCyc</a>"
  "<a href=\"pagereload\">Pagereload</a>"
  "<a href=\"server\">Server</a>"
  "<a href=\"port\">Port</a>"
  "<a href=\"hostname\">Name</a>"
  "<a href=\"led\">LED</a>"
  "<a href=\"default\">set defaults</a>"
  "<a href=\"reset\">Reset</a></p>"
  "<form method='POST' action='/update' enctype='multipart/form-data'><input type='file' name='update'><input type='submit' value='Update'></form>"
  };


const char H_CONFMENU[] PROGMEM = {
  "<a href=\"transcyc\">TransCyc</a>"
  "<a href=\"pagereload\">Pagereload</a>"
  "<a href=\"server\">Server</a>"
  "<a href=\"port\">Portnummer</a>"
  "<a href=\"hostname\">Name</a>"
  "<a href=\"led\">LED</a>"
  "<a href=\"default\">set defaults</a>"
  "<a href=\"reset\">Reset</a></p>"
  "<form method='POST' action='/update' enctype='multipart/form-data'><input type='file' name='update'><input type='submit' value='Update'></form>"
  };


const char H_RADIO_WIFI_START[] PROGMEM = {
  "<form>"
  "<p>mit welchem Netzwerk soll eine Verbindung hergestellt werden?</p>"};

const char H_RADIO_WIFI_LINE[] PROGMEM = {
  "<input type=\"radio\" name=\"SSID\" value=\"{SSID}\">  {CRYPT}{SSID}   ->   (Signal: {RSSI})"};

const char H_RADIO_WIFI_END[] PROGMEM = {
    "<br><br>"
    "<input type=\"password\" name=\"pass\"> </label>"
    "<input type=\"submit\" value=\"senden\">"
    "</form>"
  };

const char H_RADIO_LED_START[] PROGMEM = {
    "<form>"
    "<p> soll die LED ein- oder ausgeschaltet sein?</p>"
    "<input type=\"radio\" name=\"Led\" value=\"On\" {ontext}>  On"
    "<input type=\"radio\" name=\"Led\" value=\"Off\" {offtext}>  Off"};

const char H_RADIO_LED_END[] PROGMEM = {
    "<br><br>"
    "<input type=\"submit\" value=\"senden\">"
    "</form>"
  };

  const char H_NAME[] PROGMEM = {
    "<form>"
    "<p> {nametext}</p>"
    "<input type=\"text\" name=\"{urltext}\"> </label>"
    "<input type=\"submit\" value=\"senden\">"
    "</form>"
  };
